spring.application.name=inventario

spring.datasource.url=jdbc:postgresql://localhost:5432/milla_inventory
spring.datasource.username=faridparedes
spring.datasource.password=prueba2$

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
